name: Publish Latest Tag to PyPI

on:
  workflow_dispatch:  # run manually
  schedule:
    - cron: "0 3 * * *"  # OPTIONAL: run nightly (remove if undesired)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # IMPORTANT: fetch tags

      - name: Get newest tag
        id: tags
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "LATEST_TAG=$LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Checkout the newest tag
        run: git checkout $LATEST_TAG

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
